### ISSUE TITLE
handle default values by using non empty struct

### ISSUE THREAD

**Issue by petderek** [petderek/dflag#4]

**Comment by huy-vuong** [comment]
What's the `value` tag for currently then?

**Comment by petderek** [comment]
The value tag sets the default value. However, struct tags can only be constants. This, for example, is impossible:

'''
struct {
    Foo 'value:os.GetEnv("HOME")'
}
'''

What this issue would enable is to set a dynamic default like this:


val := &{Foo: os.Getenv("HOME")}
dflag.Parse(val)

**Comment by huy-vuong** [comment]
Ah, that makes sense. What would you be up to support? I'd imagine with Golang being compiled, we can't really `eval` stuff, so maybe if someone prefixed it with a magic word like `value:"env:HOME"` it'd be the equivalent of `os.GetEnv("HOME")`?

**Comment by petderek** [comment]
I like that pattern for pulling out env data! but I don't know how useful it would be in this context. I think providing this:

```
val := &{Foo: os.Getenv("HOME")}
``` 

...gives more flexibility ultimately

**Comment by petderek** [comment]
merged!
